# Generated by Django 2.2.2 on 2019-10-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='external_id',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
