# Generated by Django 2.2.2 on 2019-10-17 19:29

from django.db import migrations, models
import orchestrator.models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0002_job_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_store_location',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='working_dir',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='commandlinetooljob',
            name='status',
            field=models.IntegerField(choices=[(0, 'CREATED'), (1, 'PENDING'), (2, 'RUNNING'), (3, 'COMPLETED'), (4, 'FAILED')], default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='external_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.IntegerField(choices=[(0, 'CREATED'), (1, 'PENDING'), (2, 'RUNNING'), (3, 'COMPLETED'), (4, 'FAILED')], default=orchestrator.models.Status(0)),
        ),
    ]
