# Generated by Django 2.2.13 on 2021-04-06 18:55

from django.db import migrations, models
import orchestrator.models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0002_auto_20210405_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandlinetooljob',
            name='status',
            field=models.IntegerField(choices=[(0, 'CREATED'), (1, 'PENDING'), (2, 'RUNNING'), (3, 'COMPLETED'), (4, 'FAILED'), (5, 'ABORTED'), (6, 'UNKNOWN'), (7, 'SUSPENDED')], default=orchestrator.models.Status(0)),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.IntegerField(choices=[(0, 'CREATED'), (1, 'PENDING'), (2, 'RUNNING'), (3, 'COMPLETED'), (4, 'FAILED'), (5, 'ABORTED'), (6, 'UNKNOWN'), (7, 'SUSPENDED')], default=orchestrator.models.Status(0)),
        ),
    ]
