# Generated by Django 2.2.20 on 2021-04-20 10:28

from django.db import migrations


def migrate_statuses(apps, _):
    Job = apps.get_model("orchestrator", "Job")
    jobs = Job.objects.all()
    for job in jobs:
        if job.status > 0:
            job.status += 2
            job.save()


def revert_statuses(apps, _):
    Job = apps.get_model("orchestrator", "Job")
    jobs = Job.objects.all()
    for job in jobs:
        if job.status > 3 and job.status < 9:
            job.status -= 2
            job.save()


class Migration(migrations.Migration):

    dependencies = [
        ("orchestrator", "0003_auto_20210406_1455"),
    ]

    operations = [migrations.RunPython(migrate_statuses)]
