# Generated by Django 2.2.2 on 2019-11-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0004_auto_20191017_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='output_dir',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='root_dir',
            field=models.CharField(default='/tmp', max_length=1000),
            preserve_default=False,
        ),
    ]
