# Generated by Django 2.2.20 on 2021-05-06 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0005_auto_20210420_0632'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobCommands',
        ),
    ]
