# Generated by Django 2.2.24 on 2022-10-05 13:57

from django.db import migrations, models


def populate_walltime(apps, _):
    Job = apps.get_model("orchestrator", "Job")
    jobs = Job.objects.all()
    for job in jobs:
        if not job.walltime:
            job.walltime = 4320
            job.save()


class Migration(migrations.Migration):

    dependencies = [
        ("orchestrator", "0007_job_log_dir"),
    ]

    operations = [
        migrations.RunPython(populate_walltime),
        migrations.AlterField(
            model_name="job",
            name="walltime",
            field=models.IntegerField(default=4320),
        ),
    ]
