# Generated by Django 2.2.24 on 2022-12-22 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0009_auto_20221118_1808'),
        ('orchestrator', '0009_job_root_permission'),
    ]

    operations = [
    ]
