# Generated by Django 2.2.10 on 2020-06-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0009_auto_20200415_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.IntegerField(choices=[(0, 'CWL'), (1, 'NEXTFLOW')], default=0),
            preserve_default=False,
        ),
    ]
