# Generated by Django 2.2.10 on 2020-05-21 21:08

import orchestrator.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orchestrator', '0010_job_working_dir_clean_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandlinetooljob',
            name='status',
            field=models.IntegerField(
                choices=[(0, 'CREATED'), (1, 'PENDING'), (2, 'RUNNING'), (3, 'COMPLETED'), (4, 'FAILED'),
                         (5, 'UNKNOWN')], default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.IntegerField(
                choices=[(0, 'CREATED'), (1, 'PENDING'), (2, 'RUNNING'), (3, 'COMPLETED'), (4, 'FAILED'),
                         (5, 'UNKNOWN')], default=orchestrator.models.Status(0)),
        ),
    ]
