# Generated by Django 2.2.24 on 2023-05-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orchestrator", "0011_job_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="base_dir",
            field=models.CharField(default="/juno/res/ci/voyager/argos/", max_length=1000),
            preserve_default=False,
        ),
    ]
