# Generated by Django 2.2.10 on 2020-06-12 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0012_auto_20200604_1733'),
        ('orchestrator', '0010_job_type'),
    ]

    operations = [
    ]
