# Generated by Django 2.2.28 on 2024-06-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0012_job_base_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='output_gid',
            field=models.IntegerField(default=6146),
        ),
        migrations.AddField(
            model_name='job',
            name='output_uid',
            field=models.IntegerField(default=1741),
        ),
    ]
