# Generated by Django 2.2.24 on 2023-11-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0012_job_base_dir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='walltime',
        ),
        migrations.AddField(
            model_name='job',
            name='leader_walltime',
            field=models.IntegerField(default=168),
        ),
        migrations.AddField(
            model_name='job',
            name='tool_walltime',
            field=models.IntegerField(default=24),
        ),
    ]
