# Generated by Django 2.2.28 on 2024-06-12 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orchestrator", "0013_auto_20240611_0835"),
        ("orchestrator", "0013_auto_20231116_1546"),
    ]

    operations = []
