# Generated by Django 2.2.24 on 2023-11-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0013_add_walltime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='leader_walltime',
            field=models.IntegerField(default=7200),
        ),
        migrations.AlterField(
            model_name='job',
            name='tool_walltime',
            field=models.IntegerField(default=1440),
        ),
    ]
