# Generated by Django 2.2.28 on 2024-09-30 16:09

from django.db import migrations


def migrate_statuses(apps, schema_editor):
    Job = apps.get_model("orchestrator", "Job")
    jobs = Job.objects.all()
    for job in jobs:
        if job.status >= 1:
            job.status = job.status + 1
            job.save()


class Migration(migrations.Migration):

    dependencies = [
        ("orchestrator", "0016_auto_20240927_1228"),
    ]

    operations = [migrations.RunPython(migrate_statuses)]
