# Generated by Django 2.2.28 on 2024-11-14 21:18

from django.db import migrations, models
import orchestrator.models


class Migration(migrations.Migration):

    dependencies = [
        ("orchestrator", "0017_auto_20240930_1609"),
    ]

    def migrate_statuses(apps, _):
        Job = apps.get_model("orchestrator", "Job")
        jobs = Job.objects.all()
        for job in jobs:
            if job.status >= 6:
                job.status += 1
                job.save()

    def revert_statuses(apps, _):
        Job = apps.get_model("orchestrator", "Job")
        jobs = Job.objects.all()
        for job in jobs:
            if job.status >= 7 and job.status <= 11:
                job.status -= 1
                job.save()

    operations = [
        migrations.AlterField(
            model_name="commandlinetooljob",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "CREATED"),
                    (1, "PREPARED"),
                    (2, "SUBMITTING"),
                    (3, "SUBMITTED"),
                    (4, "PENDING"),
                    (5, "RUNNING"),
                    (6, "SET_PERMISSIONS"),
                    (7, "COMPLETED"),
                    (8, "FAILED"),
                    (9, "TERMINATED"),
                    (10, "UNKNOWN"),
                    (11, "SUSPENDED"),
                ],
                default=orchestrator.models.Status(0),
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "CREATED"),
                    (1, "PREPARED"),
                    (2, "SUBMITTING"),
                    (3, "SUBMITTED"),
                    (4, "PENDING"),
                    (5, "RUNNING"),
                    (6, "SET_PERMISSIONS"),
                    (7, "COMPLETED"),
                    (8, "FAILED"),
                    (9, "TERMINATED"),
                    (10, "UNKNOWN"),
                    (11, "SUSPENDED"),
                ],
                default=orchestrator.models.Status(0),
            ),
        ),
        migrations.RunPython(migrate_statuses, reverse_code=revert_statuses),
    ]
