# Generated by Django 2.2.28 on 2025-03-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orchestrator", "0018_auto_20241114_1618"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="log_prefix",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
