# Generated by Django 2.2.28 on 2025-03-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orchestrator", "0018_auto_20241114_1618"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="log_prefix",
            field=models.CharField(default="", max_length=30),
        ),
    ]
