# Generated by Django 2.2.28 on 2025-04-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0018_auto_20241114_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandlinetooljob',
            name='job_id',
            field=models.CharField(max_length=50),
        ),
    ]
