# Generated by Django 2.2.13 on 2021-01-29 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0018_auto_20201221_1300'),
        ('orchestrator', '0013_merge_20200612_1514'),
    ]

    operations = [
    ]
