# Generated by Django 2.2.13 on 2021-03-23 16:52

from django.db import migrations


def migrate_jobs(apps, schema_editor):
    JobOld = apps.get_model('toil_orchestrator', 'Job')
    Job = apps.get_model('orchestrator', 'Job')
    jobs = JobOld.objects.all()
    for job in jobs:
        Job.objects.create(id=job.id, type=0, app=job.app, external_id=job.external_id, root_dir=job.root_dir,
                           job_store_location=job.job_store_location,
                           resume_job_store_location=job.resume_job_store_location,
                           working_dir=job.working_dir, status=job.status, message=job.message, inputs=job.inputs,
                           outputs=job.outputs, job_store_clean_up=job.job_store_clean_up,
                           working_dir_clean_up=job.working_dir_clean_up, started=job.started,
                           submitted=job.submitted,
                           finished=job.finished, track_cache=job.track_cache)


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0019_merge_20210129_0839'),
    ]

    operations = [
        migrations.RunPython(migrate_jobs)
    ]
