# Generated by Django 2.2.28 on 2025-04-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0019_job_log_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandlinetooljob',
            name='job_id',
            field=models.CharField(max_length=50),
        ),
    ]
