# Generated by Django 2.2.28 on 2025-07-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orchestrator", "0020_auto_20250402_0942"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="user",
            field=models.CharField(default="kumarn1", max_length=100),
        ),
    ]
