# Generated by Django 2.2.28 on 2025-08-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orchestrator", "0021_job_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="output_uid",
            field=models.IntegerField(default=6146),
        ),
    ]
