# Generated by Django 2.2.28 on 2025-12-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0022_auto_20250805_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='root_permission',
            field=models.CharField(default='750', max_length=4),
        ),
    ]
