# Generated by Django 2.2.8 on 2020-01-31 20:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import toil_orchestrator.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('output_directory', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='toil_orchestrator.BaseModel')),
                ('app', django.contrib.postgres.fields.jsonb.JSONField()),
                ('external_id', models.CharField(blank=True, max_length=50, null=True)),
                ('root_dir', models.CharField(max_length=1000)),
                ('job_store_location', models.CharField(blank=True, max_length=1000, null=True)),
                ('working_dir', models.CharField(blank=True, max_length=1000, null=True)),
                ('output_dir', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.IntegerField(choices=[(0, 'CREATED'), (1, 'PENDING'), (2, 'RUNNING'), (3, 'COMPLETED'), (4, 'FAILED')], default=toil_orchestrator.models.Status(0))),
                ('inputs', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('outputs', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('job_store_clean_up', models.DateTimeField(blank=True, null=True)),
                ('track_cache', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            bases=('toil_orchestrator.basemodel',),
        ),
        migrations.CreateModel(
            name='CommandLineToolJob',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='toil_orchestrator.BaseModel')),
                ('status', models.IntegerField(choices=[(0, 'CREATED'), (1, 'PENDING'), (2, 'RUNNING'), (3, 'COMPLETED'), (4, 'FAILED')], default=0)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('submitted', models.DateTimeField(blank=True, null=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('job_name', models.CharField(max_length=100)),
                ('job_id', models.CharField(max_length=20)),
                ('details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toil_orchestrator.Job')),
            ],
            bases=('toil_orchestrator.basemodel',),
        ),
    ]
