# Generated by Django 2.2.2 on 2019-10-01 15:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('output_directory', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='toil_orchestrator.BaseModel')),
                ('app', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', models.IntegerField(choices=[(0, 'CREATED'), (1, 'PENDING'), (2, 'RUNNING'), (3, 'COMPLETED'), (4, 'FAILED')])),
                ('inputs', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('outputs', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
            ],
            bases=('toil_orchestrator.basemodel',),
        ),
        migrations.CreateModel(
            name='CommandLineToolJob',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='toil_orchestrator.BaseModel')),
                ('status', models.IntegerField(choices=[(0, 'CREATED'), (1, 'PENDING'), (2, 'RUNNING'), (3, 'COMPLETED'), (4, 'FAILED')])),
                ('job_name', models.CharField(max_length=100)),
                ('details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toil_orchestrator.Job')),
            ],
            bases=('toil_orchestrator.basemodel',),
        ),
    ]
