# Generated by Django 2.2.9 on 2020-03-10 18:57

from django.db import migrations, models
import toil_orchestrator.models


class Migration(migrations.Migration):

    dependencies = [
        ('toil_orchestrator', '0006_auto_20191125_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_store_clean_up',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='commandlinetooljob',
            name='job_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='commandlinetooljob',
            name='status',
            field=models.IntegerField(choices=[(0, 'CREATED'), (1, 'PENDING'), (2, 'RUNNING'), (3, 'COMPLETED'), (4, 'FAILED'), (5, 'UNKOWN')], default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.IntegerField(choices=[(0, 'CREATED'), (1, 'PENDING'), (2, 'RUNNING'), (3, 'COMPLETED'), (4, 'FAILED'), (5, 'UNKOWN')], default=toil_orchestrator.models.Status(0)),
        ),
    ]