# Generated by Django 2.2.10 on 2020-06-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toil_orchestrator', '0011_auto_20200521_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='submitted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
