# Generated by Django 2.2.10 on 2020-06-24 19:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import toil_orchestrator.models


class Migration(migrations.Migration):

    dependencies = [
        ("toil_orchestrator", "0013_auto_20200616_1635"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="tmp_message",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=toil_orchestrator.models.message_default),
        ),
    ]
