# Generated by Django 2.2.10 on 2020-06-22 23:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toil_orchestrator', '0013_auto_20200616_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='message',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
