# Generated by Django 2.2.10 on 2020-06-23 23:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import toil_orchestrator.models


class Migration(migrations.Migration):

    dependencies = [
        ('toil_orchestrator', '0015_auto_20200623_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='message',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=toil_orchestrator.models.message_default, null=True),
        ),
    ]
