# Generated by Django 2.2.10 on 2020-06-24 19:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import toil_orchestrator.models


class Migration(migrations.Migration):

    dependencies = [
        ("toil_orchestrator", "0015_auto_20200624_1527"),
    ]

    operations = [
        migrations.RenameField(model_name="job", old_name="message", new_name="old_message"),
        migrations.RenameField(model_name="job", old_name="tmp_message", new_name="new_message"),
    ]
