# Generated by Django 2.2.13 on 2021-04-02 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("toil_orchestrator", "0019_auto_20210330_0626"),
        ("toil_orchestrator", "0019_auto_20210330_0908"),
    ]

    operations = []
