on:
  push:
    branches: [ "feature/githubactions" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        #python -m pip install --upgrade pip
        #pip install -r requirements.txt
        #pip install toil
        #pip install cwl-utils
        #pip install cwltool
        #pip install --upgrade toil[all]
        #pip install toil-cwl-runner
        pip install --upgrade pip setuptools==57.5.0 
        pip install -r requirements.txt
        pip install -r requirements-toil.txt
        python manage.py migrate

    - name: Run migrations
      run: python manage.py migrate
    - name: Run tests
      run: python manage.py test
    env:
      RIDGEBACK_DB_NAME: github_actions
      RIDGEBACK_DB_PASSWORD: postgres
      RIDGEBACK_DB_USERNAME: postgres
      RIDGEBACK_TOIL_JOB_STORE_ROOT: /sample_path
      RIDGEBACK_TOIL_WORK_DIR_ROOT: /sample_path
      RIDGEBACK_TOIL_TMP_DIR_ROOT: /sample_path
      RIDGEBACK_LSF_WALLTIME: 10:00
      RIDGEBACK_LSF_SLA: SLA
      CELERY_LOG_PATH: /sample_path
      CELERY_PID_PATH: /sample_path
      CELERY_BEAT_SCHEDULE_PATH: /sample_path
      RIDGEBACK_NEXTFLOW_JOB_STORE_ROOT: /sample_path
      RIDGEBACK_NEXTFLOW_WORK_DIR_ROOT: /sample_path
      RIDGEBACK_NEXTFLOW_TMP_DIR_ROOT: /sample_path
      SINGULARITY_PATH: /sample_singularity
      RIDGEBACK_VENV: /sample_path
      RIDGEBACK_PATH: /sample_path
      RIDGEBACK_PORT: 4009
      RIDGEBACK_DEFAULT_QUEUE: sample_queue
      RIDGEBACK_RABBITMQ_USERNAME: sample_username
      RIDGEBACK_RABBITMQ_PASSWORD: sample_password
